name: Deploy Infrastructure with Terraform

# on:
#   push:
#     branches: main

jobs:
  terraform:
    name: Provision EC2
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Infra

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}"
